version: "3"
services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres_v15
    volumes:
      - db-data-15:/var/lib/postgresql/data/pgdata
    ports:
      - 5455:5432/tcp
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    image: odoo:16.0
    container_name: odoo_v16
    depends_on:
      - db
    ports:
      - "8070:8069/tcp"
    tty: true
    command: -- --dev=reload
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
volumes:
  db-data-15:
    driver: local
  web-data:
    driver: local
